### ISSUE TITLE
Mylar / Headphones not updating

### ISSUE THREAD

**Issue by rinzler40oz** [htpcBeginner/AtoMiC-ToolKit#151] opened 2017-04-13 15:30 UTC
I've tried both the manual update through atomic toolkit and an update through the browser. It keeps saying I'm behind on both PVRs.

**Comment by TommyE123** [comment] 2017-04-17 10:09
Hi, Thanks for logging this.

Sorry i've not replied sooner however i was quietly hoping one of the applications would have an update by now so i could do a bit of testing!

Could you update your toolkit, do a Linux update via the maintenance menu and give it another try?

If it still fails i'll look into this further. 
Do you get any error messages?
Could you give me what Linux version you are using as well.

Thanks.
Tom

**Comment by TommyE123** [comment] 2017-10-15 19:11
Closing due to not being able to reproduce the issue, not enough information given and has been outstanding for months! If you are still having trouble please create a new issue and fill out the Issue template.

Thanks

**Closed by TommyE123** 2017-10-15 19:11 UTC
Labels: Awaiting feedback, Bug
