### ISSUE TITLE
Can we set atk to update to radarr's nightly? 

### ISSUE THREAD

**Issue by samsepiol59** [htpcBeginner/AtoMiC-ToolKit#249] opened 2018-03-04 12:46 UTC
I just wanted to ask this, is it possible? The current release is not working with mono 5.10, but the nightly has been fixed. Would it be possible to change something (manually, of course) in atk's config files and make it update radarr to the nightlies, until a new radarr release is... well, released?!

**Comment by nemchik** [comment] 2018-03-04 18:23
It's not impossible, but imho it's not worth it. ATK tries to stick to stable releases. The issue is with radarr and the dev already has the fix ready and just needs to release it.

**Comment by nemchik** [comment] 2018-03-04 21:55
https://github.com/Radarr/Radarr/releases/tag/v0.2.0.995

Radarr has released the fix

**Comment by nemchik** [comment] 2018-03-05 13:12
This particular issue (again, not caused by atk) could have been solved sooner for Radarr is atk offered an update to nightly builds. The other mono apps released fixes much quicker (within 24 hours I think) and having atk switch users to nightly wouldn't have been beneficial. This really feels like a one-off scenario. Nightly builds are for advanced users, atk caters to the average-joe-user. Nightly builds would also mean more people asking atk for support on issues ATK has nothing to do with (see mono issues last week, while not nightly related, that's the kind of thing we'd see more of). For those that want nightly builds (and all the issues they can come with) it's important that they learn how to switch to the nightly builds on their own (and learn to switch back when they break).

P.s. I personally love using nightly builds and testing new features and reporting and fixing bugs when I can. I've been running the Ombi v3 and PlexPy v2 (Tautulli) from day 1 that they were made available. I have had various issues with ombi (mostly with updating it) and have contributed to the recommended 3rd party update script. I'm not saying don't use them, just that atk is here for basic installs.

**Comment by Dnkhatri** [comment] 2018-03-06 08:33
That's why I specifically asked for an option to install nightly builds not making it the default option. So only someone that wanted  the nightly build would Install it.

**Comment by TommyE123** [comment] 2018-03-06 10:41
Hi @Dnkhatri,  

Thanks for you suggestion. 

We could technically add this type of feature for most of the services that `ATK` installs, but to single out a couple of services because of a one off issue this week is possibly a slightly knee-jerk reaction in my opinion. 

I understand completely that your asking for it as optional, but I do slightly agree with @nemchik that it would cause more issues to be raised, and we simply don't have enough community support to deal with everything as it currently stands let alone supporting bleeding edge unstable builds!

Having said that I'm happy to consider it if someone wants to submit a [Pull Request](https://help.github.com/articles/about-pull-requests) to add an option to support nightly builds.
`Sonarr` appears to just need to use another repository however `Radarr` is much much more difficult to implement.

@nemchik and I are currently making the code more stable which is very nearly ready to push up. Then we will be working on the highest priority features voted for over on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit).

(you could also add it as a feature request!)

Hope this makes sense and thanks again for your suggestion.
Tom

p.s I'm going to close this now as this is technically a feature request and we are supporting features over on [Feathub](https://feathub.com/htpcBeginner/AtoMiC-ToolKit).

**Closed by TommyE123** 2018-03-06 10:41 UTC
