### ISSUE TITLE
Problem installing transmission

### ISSUE THREAD

**Issue by greekislandlover** [htpcBeginner/AtoMiC-ToolKit#10] opened 2015-09-27 07:13 UTC
Hi, trying to install this on Ubuntu trusty tahr server. I get the following error:-

--->Making some configuration changes...
sed: can't read /etc/init.d/transmission-daemon: No such file or directory
Replacing daemon username in init failed.
david@ubuntu:~/AtoMiC-ToolKit$

Any ideas please?

**Comment by mildfuzz** [comment] 2016-01-01 10:32
Getting the exact same issue. The services were not added when installing manually (i.e. without Atomic) either, so my assumption is that is where the issue is.

**Comment by htpcBeginner** [comment] 2016-01-24 14:24
Latest test with 14.04.03 worked. So closing for now.

**Closed by htpcBeginner** 2016-01-24 14:24 UTC
