### ISSUE TITLE
Transmission install problems

### ISSUE THREAD

**Issue by h0me5k1n** [htpcBeginner/AtoMiC-ToolKit#129] opened 2017-03-19 16:34 UTC
Transmission doesn't install correctly using Atomic - by default it doesn't configure the right settings.json file to be used causing transmission to be unavailable after reboot.

To replicate this issue, install transmission on a clean system and then do the following...
`systemctl stop transmission-daemon.service`
`sudo service transmission stop`
The above stops transmission processes.

Run this command...
`sudo service transmission start`

This works (if you enter login details in ~/.config/transmission-daemon/settings.json it proves that the above command starts transmission using this settings.json)

Stop this process and start transmission using systemctl...
`sudo service transmission stop`
`systemctl start transmission-daemon.service`

This is blocked by whitelist settings in /etc/transmission-daemon/settings.json

The problem is that, on boot, the second process tested above is the first that is loaded so, if you reboot, you cannot log into transmission due to the whitelist settings in etc.

I've fixed this (temporarily) by copying the settings/json file from my home directory to the /etc/transmission directory
`sudo cp ~/.config/transmission-daemon/settings.json /etc/transmission-daemon/settings.json`

**Comment by TommyE123** [comment] 2017-03-19 18:09
Hi thanks for logging an issue.

I was aware of some issues with Transmission around the settings file on older systems however wasn't aware of this. I'll take a look at what we can do to fix this. (unless you have any suggestions or maybe would like to help out by submitting a fix?!)

thanks
Tom

**Comment by TommyE123** [comment] 2017-03-20 13:27
Just a quick update to say I've managed to replicate this issue. I'm looking at a few different options to fix this however it appears the whole install is broken for init.d scripts as well. I've tried deleting the /etc/transmission-daemon/settings.json file as part of the install which appears to force it to default to ~/.config/transmission-daemon/settings.json which seems to work. I'll continue to look into this and get it sorted out so it works correctly.
Tom

**Comment by TommyE123** [comment] 2017-03-28 08:42
This should now be fixed in the master branch. If anyone can confirm its now ok for them it would be great.

**Comment by TommyE123** [comment] 2017-04-02 13:20
Closing as I believe this is now resolved.

**Comment by TommyE123** [comment] 2017-04-02 17:15
Typically its just failed the new integration tests i've created so will need some further investigation.

**Comment by TommyE123** [comment] 2017-04-03 20:17
False alarm, was caused by a missing constant reset that could have affected any application.

**Closed by TommyE123** 2017-04-03 20:17 UTC
Labels: Bug, Priority: High
