### ISSUE TITLE
SickRage install fails not finding autoProcessTV/autoProcessTV.cfg.sample

### ISSUE THREAD

**Issue by htpcBeginner** [htpcBeginner/AtoMiC-ToolKit#29] opened 2015-11-19 20:18 UTC
http://www.htpcbeginner.com/atomic-toolkit/#comment-5004

**Comment by ZaLiTHkA** [comment] 2015-11-19 20:57
I believe this might be a duplicate of #25.. I saw the post a few days back, but I haven't had a chance to check it myself yet.

**Comment by Phobix** [comment] 2015-11-23 06:46
also having this issue

**Comment by Phobix** [comment] 2015-11-23 07:07
I found the issue. The sickrage git no longer has the AutoProcessTV folder. I was able to edit the sickrage install script to use an alternative file location that contained the .cfg.example it was looking for. Just go into the sickrage install script and look for the correct line and edit accordingly.

**Comment by htpcBeginner** [comment] 2015-11-25 01:09
@Phobix where did you find the autoProcessTV.cfg.example file?

**Comment by Phobix** [comment] 2015-11-25 04:10
github, just search for the file. I can also upload here if needed.

**Comment by htpcBeginner** [comment] 2015-11-27 20:18
@Phobix there is no autoProcessTV.cfg.sample file in SickRage. I couldn't find it. That is why I asked for the specific path.

**Comment by htpcBeginner** [comment] 2015-11-27 20:19
Fixed in development branch. The script now looks for autoProcessTV.cfg.sample file. If not found, it moves on with installation without erroring out.

**Comment by Phobix** [comment] 2015-11-27 21:26
Are you just having it auto create its own? Its only like 5 lines, can just have the script create the needed file.

**Comment by htpcBeginner** [comment] 2015-11-27 22:12
Yes, but the question is is autoProcessTV.cfg file need anymore? There should be a reason why it was removed from SickRage. 

Right now (with the fix) the script just ignores if it is not found.

**Closed** 2015-12-08 14:53 UTC
