### ISSUE TITLE
Sonarr install broken

### ISSUE THREAD

**Issue by kunallanjewar** [htpcBeginner/AtoMiC-ToolKit#196] opened 2017-09-18 00:38 UTC
--->Mono installation complete.

--->Installing Sonarr...
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package nzbdrone

**Comment by TommyE123** [comment] 2017-09-18 15:45
This looks like it possibly didn't add the repository correctly. 
Can you see if you got any other errors before this one?
What Linux version are you running?

Thanks
Tom

**Comment by TommyE123** [comment] 2017-10-15 18:52
Closing due to not being able to reproduce the issue, not enough information given and has been outstanding for a month. If you are still having trouble please create a new issue and fill out the Issue template.

Thanks

**Closed by TommyE123** 2017-10-15 18:52 UTC
Labels: Awaiting feedback, Bug
